/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegmentationRouteImport } from './routes/segmentation'
import { Route as RecommendationRouteImport } from './routes/recommendation'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as IndexRouteImport } from './routes/index'

const SegmentationRoute = SegmentationRouteImport.update({
  id: '/segmentation',
  path: '/segmentation',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationRoute = RecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prediction': typeof PredictionRoute
  '/recommendation': typeof RecommendationRoute
  '/segmentation': typeof SegmentationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prediction': typeof PredictionRoute
  '/recommendation': typeof RecommendationRoute
  '/segmentation': typeof SegmentationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prediction': typeof PredictionRoute
  '/recommendation': typeof RecommendationRoute
  '/segmentation': typeof SegmentationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prediction' | '/recommendation' | '/segmentation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prediction' | '/recommendation' | '/segmentation'
  id: '__root__' | '/' | '/prediction' | '/recommendation' | '/segmentation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PredictionRoute: typeof PredictionRoute
  RecommendationRoute: typeof RecommendationRoute
  SegmentationRoute: typeof SegmentationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segmentation': {
      id: '/segmentation'
      path: '/segmentation'
      fullPath: '/segmentation'
      preLoaderRoute: typeof SegmentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation': {
      id: '/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof RecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PredictionRoute: PredictionRoute,
  RecommendationRoute: RecommendationRoute,
  SegmentationRoute: SegmentationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
